# Generated by Django 3.2.15 on 2022-10-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200625_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
